import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {


  const handlerSubmit = async (event: any) => {
    event.preventDefault();
    //const name = document.querySelector('#ruc').value;
    const data = {
      ruc: event.target.ruc.value,
    }
    
    if (!data.ruc) {
      alert('El ruc es obligatorio')
      return false
    }

    const options = {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
      //body: JSON.stringify(data),
    }

    const response = await fetch('http://localhost:3000/api/consultation/' + data.ruc, options)

    // Get the response data from server as JSON.
    // If server returns the name submitted, that means the form works.
    const result = await response.json()
    console.log("result ==> ", result)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <form onSubmit={handlerSubmit}>
          <label>Ruc:</label>
          <input type="text" id="ruc" value={"20511315922"}/>
          <button type='submit'>Enviar</button>
        </form>
      </main>
    </>
  )
}


